import { Client, Order, PhoneLog, MemberStatus } from '../types';

export const mockClients: Client[] = [
  {
    familyNumber: 'f1',
    searchKey: 'johndoe1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    address: '123 Main St',
    aptNumber: '',
    zipCode: '12345',
    phone1: '(555) 123-4567',
    phone2: '',
    isUnhoused: false,
    isTemporary: false,
    adults: 1,
    schoolAged: 0,
    smallChildren: 0,
    temporaryMembers: {
      adults: 0,
      schoolAged: 0,
      smallChildren: 0
    },
    familySize: 1,
    foodNotes: 'Prefers gluten-free items',
    officeNotes: '',
    totalVisits: 5,
    totalThisMonth: 1,
    connectedFamilies: [],
    memberStatus: MemberStatus.Active,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15'),
    lastVisit: new Date('2023-03-10')
  },
  {
    familyNumber: 'f2',
    searchKey: 'janesmith2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    address: '456 Oak Ave',
    aptNumber: '',
    zipCode: '67890',
    phone1: '(555) 987-6543',
    phone2: '',
    isUnhoused: false,
    isTemporary: false,
    adults: 2,
    schoolAged: 0,
    smallChildren: 0,
    temporaryMembers: {
      adults: 0,
      schoolAged: 0,
      smallChildren: 0
    },
    familySize: 2,
    foodNotes: 'Allergic to peanuts',
    officeNotes: '',
    totalVisits: 3,
    totalThisMonth: 0,
    connectedFamilies: [],
    memberStatus: MemberStatus.Active,
    createdAt: new Date('2023-02-01'),
    updatedAt: new Date('2023-02-01'),
    lastVisit: new Date('2023-02-15')
  },
  {
    familyNumber: 'f3',
    searchKey: 'bobjohnson3',
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@example.com',
    address: '789 Pine Rd',
    aptNumber: '',
    zipCode: '54321',
    phone1: '(555) 555-5555',
    phone2: '',
    isUnhoused: true,
    isTemporary: true,
    adults: 2,
    schoolAged: 2,
    smallChildren: 0,
    temporaryMembers: {
      adults: 1,
      schoolAged: 1,
      smallChildren: 0
    },
    familySize: 5,
    foodNotes: 'Prefers gluten-free options',
    officeNotes: '',
    totalVisits: 2,
    totalThisMonth: 1,
    connectedFamilies: [],
    memberStatus: MemberStatus.Inactive,
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2023-03-01'),
    lastVisit: new Date('2023-03-15')
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    familySearchId: '1',
    status: 'pending',
    notes: 'Gluten-free items requested',
    pickupDate: '2024-03-20',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2',
    familySearchId: '2',
    status: 'scheduled',
    notes: 'Client requested low-sodium options',
    pickupDate: '2023-04-02',
    createdAt: new Date('2023-03-26'),
    updatedAt: new Date('2023-03-26'),
  },
  {
    id: '3',
    familySearchId: '3',
    status: 'scheduled',
    notes: 'Client requested gluten-free options',
    pickupDate: '2023-04-03',
    createdAt: new Date('2023-03-27'),
    updatedAt: new Date('2023-03-27'),
  },
  {
    id: '4',
    familySearchId: '1',
    status: 'picked_up',
    notes: 'Client picked up on time',
    pickupDate: '2023-03-20',
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-20'),
  },
];

export const mockPhoneLogs: PhoneLog[] = [
  {
    id: '1',
    familySearchId: '1',
    phoneNumber: '(555) 123-4567',
    callType: 'incoming',
    callOutcome: 'completed',
    notes: 'Requested food assistance',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: '2',
    familySearchId: '2',
    phoneNumber: '555-987-6543',
    callType: 'outgoing',
    callOutcome: 'voicemail',
    notes: 'Left message about order status',
    createdAt: new Date('2023-03-23'),
    updatedAt: new Date('2023-03-23'),
  },
  {
    id: '3',
    familySearchId: '3',
    phoneNumber: '555-555-5555',
    callType: 'incoming',
    callOutcome: 'no_answer',
    notes: 'No answer, will try again later',
    createdAt: new Date('2023-03-24'),
    updatedAt: new Date('2023-03-24'),
  },
]; 